### ISSUE TITLE
[IC-123] refactor: 백엔드 엔드포인트 정리 및 MSA 아키텍쳐 분리 리팩토링

### ISSUE THREAD

**Issue by inpyu** [money-driven-development/rocket23#103]
## Target Period
1/29 - 2/2

## Summary
각각 다른 형식으로 혼용되어 있는 백엔드 API 정리 및 여러 항목이 혼재되어 있는 스캔 히스토리 모듈 분리

## Branch
refactor/#103-endpoint-divide-main

## Target Commit Message
- chore : 엔드포인트 통일
- refactor: 스캔 히스토리 모듈 분리

## Detail
- rocket / rocket23으로 다양하게 사용하고 있는 엔드포인트 통일
- 경로 또한 주관적 기준에 따라 사용하고 있던 각종 엔드포인트를 Restful API 규칙에 맞게 통일
- Scan History 모듈을 MSA 아키텍쳐로 분리할 수 있도록 분리가 가능한 아키텍쳐 파악 및 모듈 분리

**Comment by Floodnut** [comment]
이거 지라 사용하고 있으면 이렇게 이슈 이제 번거롭게 만들지말고 지라 티켓으로만 관리하는건 어떤가요?
이슈는 정말 문제가 있거나 제안 사항 등이 있을때 사용하고요
